### ISSUE TITLE
Add number of available pages in pagination

### ISSUE THREAD

**Issue by bahiirwa** [TukuToi/tukutoi-cp-directory-integration#3]
While using the plugin, I felt like I had an unlimited options (This might be intended)
I was overwhelmed not knowing where the end is.
My request is to add number of available pages in pagination like in the screenshot. Thank you.

![Screenshot(8)](https://user-images.githubusercontent.com/7713923/175868030-46d384fc-dac0-499f-8212-00757c1b3c3c.png)

**Comment by smileBeda** [comment]
I omitted this because the amount of code needed, to produce one single number that helps nothing in the actual feature, was hilarious, and it adds the to the pagination length.

I will see if I can change that to what you suggest (which is basically the same as WP core does, and I find it useless, because no one wants to know about _pages_, they want to know about _plugns_...).
For that added to next milestone, but no promises.

_The main focus is to get the GitHub Download integration working, which adds functionality, and allows to download/update made by TukuToi not listed on the directory, since the directory for my personal opinion is attempting to _own_ the plugins, even thou it is just a directory, and requires too much manual work to maintain for a busy developer._

**Comment by smileBeda** [comment]
@bahiirwa - The pagination total has been added as suggested, can be tested in https://github.com/TukuToi/tukutoi-cp-directory-integration/tree/1.2.0

**Comment by bahiirwa** [comment]
This is solved thanks.
